src/main/java/com/matchday/matchdayserver/testdomain/controller/AppController.java
feat1->release pr close 후 github action 동작 테스트 용 PR
=> chore: PR 생성을 위한 더미 커밋

.github/workflows/deploy.yml, .github/workflows/test.yml
Overview
github action 스크립트 파일 (deploy.yml,test.yml) 에 캐싱 코드 추가
Review Request
캐싱이 유효하게 적용될지
Reference
https://kotlinworld.com/399
https://kingofbackend.tistory.com/263
=> chore(ci): Gradle 캐시 적용하기 위해 deploy.yml 수정

src/main/java/com/matchday/matchdayserver/testdomain/controller/AppController.java
=> CI/CD캐시 확인을 위한 더미 PR

.github/workflows/deploy.yml, .github/workflows/test.yml
소스코드 변경 외에는 테스트 생략하도록 test.yml 조건 분기 추가
deploy.yml test.yml 에서 불필요한 디버깅용 코드 제거
test.yml에 paths 조건 추가해서 소스코드 이외의 내용 PR (ex Readme) 는 테스트 스킵되도록 변경한 사항 
https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions?utm_source=chatgpt.com
=> 소스코드 변경 외에는 테스트 생략하도록 test.yml 조건 분기 추가

.gitignore, build.gradle, src/main/java/com/matchday/matchdayserver/common/exception/ApiException.java, src/main/java/com/matchday/matchdayserver/common/exception/ApiExceptionHandler.java, src/main/java/com/matchday/matchdayserver/common/exception/ApiExceptionInterface.java, src/main/java/com/matchday/matchdayserver/common/response/ApiResponse.java, src/main/java/com/matchday/matchdayserver/common/response/DefaultStatus.java, src/main/java/com/matchday/matchdayserver/common/response/StatusInterface.java, src/main/resources/application.yml
close : #17 
- 공통 ApiResponse는 Controller에서 ApiResponse<Generic> 형태로 반환할 때 사용
```java
ApiResponse.ok(data);
```
- ApiException 사용예시
```java
throw new ApiException(StatusInterface);
```
- success 
- error
=> 공통 Response, Exception, Status Interface 구현

src/main/java/com/matchday/matchdayserver/common/exception/ApiExceptionHandler.java
=> fix: api exception handler에서 status code 변경 안되던 부분 수정 및 Exception 임시로 핸들링 하도록 추가

.github/workflows/envtest.yml, src/main/java/com/matchday/matchdayserver/user/service/UserService.java
=> chore:env 파일 확인 위한 임시 워크플로우 작성

src/main/java/com/matchday/matchdayserver/match/model/entity/Match.java, src/main/java/com/matchday/matchdayserver/match/repository/MatchRepository.java
MAT-31
Match Entity 생성
- homeTeam, awayTeam의 fetch를 우선은 보수적으로 하는게 나을 것 같아 LAZY로 설정했습니다.
- 전체적인 코드 및 네이밍 스타일 문제점 있으면 말씀해주세요!
=> [MAT-31] Match Entity 구현

src/main/java/com/matchday/matchdayserver/common/response/MatchStatus.java, src/main/java/com/matchday/matchdayserver/match/controller/MatchController.java, src/main/java/com/matchday/matchdayserver/match/model/dto/request/MatchCreateRequest.java, src/main/java/com/matchday/matchdayserver/match/service/MatchCreateService.java, src/main/java/com/matchday/matchdayserver/match/service/MatchService.java
[MAT-33](https://match-day.atlassian.net/browse/MAT-33)
MATCH 등록 구현
매치 등록시 예외처리 로직을 service의 각 메서드로 구현을 했는데, 코드가 길어진 것 같다는 생각이 드네요 ㅠㅠ 
해당 부분 및 전체적인 코드 피드백 부탁드리겠습니다 
[등록 성공]
[예외 발생]
- 경기명 미기입
- 존재하지 않는 팀
- 홈 팀과 어웨이 팀이 동일할 경우
- 경기장 미기입
- 경기 일자가 과거 날짜인 경우
- 경기 시작 시간이 종료 시간보다 늦을 경우
[MAT-33]: https://match-day.atlassian.net/browse/MAT-33?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MAT-33] Match 등록

src/main/java/com/matchday/matchdayserver/user/service/UserService.java
NCP 서버 이전 후 url 변동으로 인해 secret.key 및 env 수정하고
CI/CD 정상작동 확인 위한 테스트용 PR
Optional
=> [MAT-71] NCP 서버 이전 테스트

src/main/java/com/matchday/matchdayserver/user/service/UserService.java
=> [MAT-71] workflow test 2

.github/workflows/deploy.yml, .github/workflows/test.yml, src/main/java/com/matchday/matchdayserver/user/service/UserService.java
workflow .env 파일 생성 확인 위한 로그 추가
=> [MAT-71] workflow test 3

.github/workflows/deploy.yml
=> [MAT-71] workflow test 4

src/main/java/com/matchday/matchdayserver/user/service/UserService.java
=> [MAT-71] workflow test 5

.github/workflows/deploy.yml
deploy.yml env 파일도 전송되게 변경 , 진짜 너무 자고싶다
=> [MAT-71] workflow test 6

.github/workflows/deploy.yml
deploy.yml env 파일도 전송되게 변경 , 하...
=> [MAT-71] workflow test 7

.github/workflows/deploy.yml
deploy.yml env 파일도 전송되게 변경 , ^^
=> [MAT-71] workflow test 8

.github/workflows/deploy.yml
=> [MAT-71] workflow test END

build.gradle, src/main/resources/application.yml
implementation 'io.github.cdimascio:java-dotenv:5.2.2' 의존성 추가
=> [MAT-71] workflow test 9

.github/workflows/deploy.yml, .gitignore, src/main/resources/application.yml
=> [MAT-71] github action에서 application.yml에 값을 직접 로드하도록 수정

.github/workflows/deploy.yml, src/main/resources/application.yml
=> [MAT-71] human err 오타수정

src/main/java/com/matchday/matchdayserver/config/WebConfig.java
=> [MAT-76] WebConfig CORS 추가

.github/workflows/deploy.yml
=> Feat(deploy): AWS 정보 추가

src/main/java/com/matchday/matchdayserver/matchevent/common/MatchEventConstants.java, src/main/java/com/matchday/matchdayserver/matchevent/service/MatchEventSaveService.java, src/main/java/com/matchday/matchdayserver/matchuser/service/MatchUserExchangeService.java
Related to : https://match-day.atlassian.net/jira/software/projects/MAT/boards/2
- 하드코딩되있던 값 Codebase로 수정
=> [MAT-236] 유저 이벤트 생성 시 Log 전송 안되는 버그 수정

src/main/java/com/matchday/matchdayserver/matchevent/mapper/MatchEventMapper.java
https://match-day.atlassian.net/browse/MAT-254
=> [MAT-254] 하드코딩 개선

src/main/java/com/matchday/matchdayserver/common/Constants.java, src/main/java/com/matchday/matchdayserver/config/WebConfig.java
X
https://dev.matchday-planner.com/
https://matchday-planner.com/
로 프론트 주소 변경 예정에 대한 대응
=> feat: CORS 설정

src/main/java/com/matchday/matchdayserver/auth/entity/RefreshToken.java
https://match-day.atlassian.net/browse/MAT-313
- Refresh 토큰 엔티티 추가
=> [MAT-313] Db migration v8

src/main/java/com/matchday/matchdayserver/auth/entity/RefreshToken.java, src/main/java/com/matchday/matchdayserver/common/Aspect/CheckMatchAspect.java, src/main/java/com/matchday/matchdayserver/common/Aspect/CheckTeamAspect.java, src/main/java/com/matchday/matchdayserver/common/annotation/CheckMatch.java, src/main/java/com/matchday/matchdayserver/common/annotation/CheckTeam.java, src/main/java/com/matchday/matchdayserver/common/auth/CustomAccessDeniedHandler.java, src/main/java/com/matchday/matchdayserver/common/exception/ApiExceptionHandler.java, src/main/java/com/matchday/matchdayserver/common/response/AnnotationStatus.java, src/main/java/com/matchday/matchdayserver/common/response/AuthStatus.java, src/main/java/com/matchday/matchdayserver/common/response/DefaultStatus.java, src/main/java/com/matchday/matchdayserver/config/SecurityConfig.java, src/main/java/com/matchday/matchdayserver/config/SwaggerConfig.java, src/main/java/com/matchday/matchdayserver/user/controller/UserController.java, src/main/java/com/matchday/matchdayserver/user/model/dto/request/UpdateUserRoleRequest.java, src/main/java/com/matchday/matchdayserver/user/model/dto/response/UpdateUserRoleResponse.java, src/main/java/com/matchday/matchdayserver/user/model/entity/User.java, src/main/java/com/matchday/matchdayserver/user/model/enums/Role.java, src/main/java/com/matchday/matchdayserver/user/service/UserOpenApiService.java, src/main/java/com/matchday/matchdayserver/user/service/UserService.java
https://match-day.atlassian.net/browse/MAT-333
- 권한 체크 어노테이션 추가 및 Role 계층관계가 정의되었습니다 노션 링크를 확인해주세요
https://www.notion.so/API-20b2d4402f5580ee94b3c841b375c555?source=copy_link
- 유저에게 권한을 부여할수 있는 API가 추가되었습니다
=> [MAT-333] 권한 체크 어노테이션 구현

src/main/java/com/matchday/matchdayserver/team/controller/TeamController.java, src/main/java/com/matchday/matchdayserver/team/service/TeamService.java, src/main/java/com/matchday/matchdayserver/user/controller/UserController.java, src/main/java/com/matchday/matchdayserver/user/model/dto/request/UserJoinTeamRequest.java
https://match-day.atlassian.net/browse/MAT-314
https://match-day.atlassian.net/browse/MAT-315
- 각 엔트포인트에 권한 검증 로직이 추가되었습니다
- 팀 생성 시 생성자와 팀 사이에 연결테이블이 생성됩니다
=> [MAT-314][MAT-315] Team,User 도메인 auth 적용

src/main/java/com/matchday/matchdayserver/match/controller/MatchController.java, src/main/java/com/matchday/matchdayserver/match/model/dto/request/MatchCreateRequest.java, src/main/java/com/matchday/matchdayserver/matchevent/controller/MatchEventHistoryController.java, src/main/java/com/matchday/matchdayserver/matchevent/model/dto/MatchEventRequest.java, src/main/java/com/matchday/matchdayserver/matchevent/model/dto/MatchEventUserRequest.java, src/main/java/com/matchday/matchdayserver/matchuser/controller/MatchUserController.java, src/main/java/com/matchday/matchdayserver/matchuser/model/dto/MatchUserCreateRequest.java, src/main/java/com/matchday/matchdayserver/matchuser/service/MatchUserService.java, src/main/java/com/matchday/matchdayserver/team/service/TeamService.java, src/main/java/com/matchday/matchdayserver/user/service/UserService.java, src/main/resources/application.yml, src/test/java/com/matchday/matchdayserver/matchuser/controller/MatchuserControllerCreateTest.java
[MAT-316](https://match-day.atlassian.net/jira/software/projects/MAT/boards/2?selectedIssue=MAT-316)
[MAT-317](https://match-day.atlassian.net/jira/software/projects/MAT/boards/2?selectedIssue=MAT-314)
- MatchUser 도메인 auth 적용
- Match 도메인 auth 적용
- MatchUserCreate Test 코드 작성
[MAT-316]: https://match-day.atlassian.net/browse/MAT-316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MAT-317]: https://match-day.atlassian.net/browse/MAT-317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MAT-316,317] MatchUser, Match 도메인 auth 적용

.github/workflows/deploy.yml, .github/workflows/test.yml, src/main/resources/application-test.yml
x
- workflow에 auth 관련 키를 받을 수 있게 변경하였습니다
- application-test.yml 이 auth 관련 키를 받을 수 있게 변경하였습니다
=> feat: workflow auth 코드 추가

.github/workflows/test.yml, src/test/java/com/matchday/matchdayserver/user/controller/UserControllerTest.java
x
- auth 관련 토큰을 적용한 후 userControllerCreateTest 가 오류없이 잘 테스트되는지 확인하기 위한 pr입니다
Optional
=> chore: build test
